name: volunteer_connect
description: A Flutter application designed to connect local volunteers with community events and charity initiatives.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# All packages from pub.dev go here, at the same indentation level.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: 4.2.0
  
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  image_picker: ^1.2.0
  firebase_storage: ^13.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

# This section is only for Flutter-specific configurations like assets and fonts.
flutter:
  uses-material-design: true
  assets:
    - assets/images/