// lib/firebase_options.dart (FIXED)

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIs9SfuSLaHbrlevyv8upQujnOv_1CmXY',
    appId: '1:12147009257:web:6a226bad307006e3bef278',
    messagingSenderId: '12147009257',
    projectId: 'volunteerconnect-5459a',
    authDomain: 'volunteerconnect-5459a.firebaseapp.com',
    storageBucket: 'volunteerconnect-5459a.firebasestorage.app',
    measurementId: 'G-2NFM1WP8C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZomUxhJenT8ezA05RU_f-eVfRfYchvhQ',
    appId: '1:12147009257:android:9e8500fa64f10775bef278',
    messagingSenderId: '12147009257',
    projectId: 'volunteerconnect-5459a',
    storageBucket: 'volunteerconnect-5459a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsUqCqpUwr6BzRsF_OxNNECm8KViY01qU',
    appId: '1:12147009257:ios:4d02e4306e8d0dcdbef278',
    messagingSenderId: '12147009257',
    projectId: 'volunteerconnect-5459a',
    storageBucket: 'volunteerconnect-5459a.firebasestorage.app',
    iosBundleId: 'com.example.volunteerconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsUqCqpUwr6BzRsF_OxNNECm8KViY01qU',
    appId: '1.12147009257:ios:4d02e4306e8d0dcdbef278',
    messagingSenderId: '12147009257',
    projectId: 'volunteerconnect-5459a',
    storageBucket: 'volunteerconnect-5459a.firebasestorage.app',
    iosBundleId: 'com.example.volunteerconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIs9SfuSLaHbrlevyv8upQujnOv_1CmXY',
    appId: '1.12147009257:web:04b8c1e6289bb681bef278',
    messagingSenderId: '12147009257',
    projectId: 'volunteerconnect-5459a',
    authDomain: 'volunteerconnect-5459a.firebaseapp.com',
    storageBucket: 'volunteerconnect-5459a.firebasestorage.app',
    measurementId: 'G-T264BKJFS9',
  );
}